name: "WordPress Plugin Build"
description: "Build an upload the zip of a plugin"
author: "Josh"
inputs:
  generate-zip:
    description: "Generate package zip file?"
    default: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.generate-zip }}
branding:
  icon: "upload-cloud"
  color: "blue"
